### ISSUE TITLE
sample.fa

### ISSUE THREAD

**Issue by vineetbansal** [alexviiia/dpuc2#1]
Hello,
I'm trying to follow along the README to get the software to work end-end. It seems to me that a `sample.fa` in the repo would help to follow along? If there's any other standard `*.fa` file that one can use to verify the software please let me know.

Admittedly, I know very little of the domain but am just trying to validate the dpuc2 software in a deployment setting. I'm using files from Pfam32.0, in case it helps.

**Comment by alexviiia** [comment]
Dear Vineet, I have added sample files to this repository.  They correspond with Pfam 32.  Thank you for helping me improve the repository!

**Comment by vineetbansal** [comment]
This is excellent! (especially for software folks like me who have no "real" data) Thanks @alexviiia
